In [9]:
pip install --upgrade pip

Requirement already satisfied: pip in c:\users\simran\anaconda3\lib\site-packages (24.2)
Collecting pip
  Downloading pip-25.0.1-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-25.0.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------  1.8/1.8 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 9.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
Successfully installed pip-25.0.1
Note: you may need to restart the kernel to use updated packages.

In [10]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\simran\anaconda3\lib\site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import os

In [4]:
folder_path = "March"
all_data =[]

In [5]:
columns_to_keep = [
    'Time', 'EacToday(kWh)', 'EacTotal(kWh)', 'Ppv(W)', 'EpvToday(kWh)', 'EpvTotal(kWh)', 'TimeTotal(S)',
    'IacR(A)', 'IacS(A)', 'IacT(A)', 'PacR(VA)', 'PacS(VA)', 'PacT(VA)', 
    'VacR(V)', 'VacS(V)', 'VacT(V)', 'Pac(W)', 'INVTemp(℃)', 'AMTemp1(℃)', 
    'BTTemp(℃)', 'OUTTemp(℃)', 'AMTemp2(℃)', 'ReactPower(Var)', 
    'ReactPowerMax(Var)', 'ReactPower_Total(kWh)'
]

In [11]:
for filename in os.listdir(folder_path):
    if filename.endswith('.xls'):
        file_path = os.path.join(folder_path, filename)
        try:
            # Skip first 3 metadata rows
            df = pd.read_excel(file_path, skiprows=3)

            # Keep only the needed columns
            df = df[columns_to_keep]

            all_data.append(df)
        except Exception as e:
            print(f"❌ Error processing {filename}: {e}")

In [12]:
print(type(all_data))

<class 'list'>

In [14]:
combined_df = pd.concat(all_data, ignore_index=True)

In [18]:
combined_df

,Time,EacToday(kWh),EacTotal(kWh),Ppv(W),EpvToday(kWh),EpvTotal(kWh),TimeTotal(S),IacR(A),IacS(A),IacT(A),...,VacT(V),Pac(W),INVTemp(℃),AMTemp1(℃),BTTemp(℃),OUTTemp(℃),AMTemp2(℃),ReactPower(Var),ReactPowerMax(Var),ReactPower_Total(kWh)
0,2025-03-01 06:52:01,0.0,323720.4,405.7,0.0,632154.1,33110887.5,0.0,0.0,0.0,...,245.3,0.0,25.3,23.9,32.3,0,23.2,0.0,38750,1228.8
1,2025-03-01 06:57:01,0.0,323720.4,106.4,0.0,632154.1,33110986.0,0.5,0.6,0.6,...,244.6,104.9,26.5,25.4,33.1,0,23.5,1533.5,38750,1228.8
2,2025-03-01 07:02:01,0.0,323720.4,106.8,0.0,632154.1,33111287.0,0.7,0.7,0.6,...,244.8,105.2,27.6,27.1,34.0,0,23.9,1476.3,38750,1228.9
3,2025-03-01 07:07:01,0.0,323720.4,418.7,0.0,632154.1,33111584.5,0.8,0.8,0.8,...,244.1,412.5,28.8,28.6,35.2,0,24.0,1471.0,38750,1229.0
4,2025-03-01 07:12:01,0.0,323720.4,752.1,0.0,632154.1,33111887.0,1.4,1.6,1.7,...,243.1,740.9,29.8,30.0,36.0,0,24.2,1329.8,38750,1229.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4627,2025-03-31 18:54:02,526.4,340025.0,154.1,1029.4,664019.3,34497957.0,0.7,0.8,0.7,...,256.4,151.8,55.1,49.1,58.5,0,43.3,1520.2,38750,1272.9
4628,2025-03-31 18:59:02,526.5,340025.1,80.8,1029.4,664019.3,34498254.0,0.6,0.6,0.6,...,256.5,79.6,54.6,49.7,58.3,0,42.6,1480.4,38750,1273.0
4629,2025-03-31 19:04:02,526.5,340025.1,2.7,1029.4,664019.3,34498558.0,0.6,0.7,0.7,...,255.7,2.7,54.2,48.7,57.7,0,43.1,1530.0,38750,1273.1
4630,2025-03-31 19:09:02,526.5,340025.1,6.1,1029.4,664019.3,34498852.0,0.7,0.7,0.6,...,255.9,6.1,53.6,47.9,56.9,0,43.2,1522.6,38750,1273.3
4631,2025-03-31 19:14:03,526.5,340025.1,0.0,1029.4,664019.3,34499154.5,0.7,0.8,0.7,...,255.9,0.0,54.0,48.5,56.4,0,42.6,1505.5,38750,1273.4

In [19]:
# Parse 'Time' column to datetime
combined_df['Time'] = pd.to_datetime(combined_df['Time'], errors='coerce')

In [20]:
combined_df

,Time,EacToday(kWh),EacTotal(kWh),Ppv(W),EpvToday(kWh),EpvTotal(kWh),TimeTotal(S),IacR(A),IacS(A),IacT(A),...,VacT(V),Pac(W),INVTemp(℃),AMTemp1(℃),BTTemp(℃),OUTTemp(℃),AMTemp2(℃),ReactPower(Var),ReactPowerMax(Var),ReactPower_Total(kWh)
0,2025-03-01 06:52:01,0.0,323720.4,405.7,0.0,632154.1,33110887.5,0.0,0.0,0.0,...,245.3,0.0,25.3,23.9,32.3,0,23.2,0.0,38750,1228.8
1,2025-03-01 06:57:01,0.0,323720.4,106.4,0.0,632154.1,33110986.0,0.5,0.6,0.6,...,244.6,104.9,26.5,25.4,33.1,0,23.5,1533.5,38750,1228.8
2,2025-03-01 07:02:01,0.0,323720.4,106.8,0.0,632154.1,33111287.0,0.7,0.7,0.6,...,244.8,105.2,27.6,27.1,34.0,0,23.9,1476.3,38750,1228.9
3,2025-03-01 07:07:01,0.0,323720.4,418.7,0.0,632154.1,33111584.5,0.8,0.8,0.8,...,244.1,412.5,28.8,28.6,35.2,0,24.0,1471.0,38750,1229.0
4,2025-03-01 07:12:01,0.0,323720.4,752.1,0.0,632154.1,33111887.0,1.4,1.6,1.7,...,243.1,740.9,29.8,30.0,36.0,0,24.2,1329.8,38750,1229.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4627,2025-03-31 18:54:02,526.4,340025.0,154.1,1029.4,664019.3,34497957.0,0.7,0.8,0.7,...,256.4,151.8,55.1,49.1,58.5,0,43.3,1520.2,38750,1272.9
4628,2025-03-31 18:59:02,526.5,340025.1,80.8,1029.4,664019.3,34498254.0,0.6,0.6,0.6,...,256.5,79.6,54.6,49.7,58.3,0,42.6,1480.4,38750,1273.0
4629,2025-03-31 19:04:02,526.5,340025.1,2.7,1029.4,664019.3,34498558.0,0.6,0.7,0.7,...,255.7,2.7,54.2,48.7,57.7,0,43.1,1530.0,38750,1273.1
4630,2025-03-31 19:09:02,526.5,340025.1,6.1,1029.4,664019.3,34498852.0,0.7,0.7,0.6,...,255.9,6.1,53.6,47.9,56.9,0,43.2,1522.6,38750,1273.3
4631,2025-03-31 19:14:03,526.5,340025.1,0.0,1029.4,664019.3,34499154.5,0.7,0.8,0.7,...,255.9,0.0,54.0,48.5,56.4,0,42.6,1505.5,38750,1273.4

In [21]:
combined_df = combined_df.dropna(subset=['Time'])
combined_df.shape

(4632, 25)

In [22]:
combined_df.to_csv('march_cleaned.csv', index=False)